# Generated by Django 5.2 on 2025-04-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('cast', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=15)),
                ('listed_in', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
